"""init

Revision ID: 5f588ebba530
Revises: 
Create Date: 2025-12-04 18:45:58.650353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f588ebba530'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=50), nullable=False, comment='字符串类型主键'),
    sa.Column('username', sa.String(length=100), nullable=False, comment='统一显示名称'),
    sa.Column('password_hash', sa.String(length=255), nullable=True, comment='密码哈希（仅管理员需要）'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='头像URL'),
    sa.Column('role', sa.Enum('buyer', 'merchant', 'admin', 'platform', name='userrole'), nullable=False, comment='用户角色：buyer/merchant/admin/platform'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述信息'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态：active/inactive'),
    sa.Column('created_at', sa.Integer(), nullable=True, comment='创建时间戳'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False, comment='自增主键'),
    sa.Column('participant1_id', sa.String(length=50), nullable=False, comment='会话参与者1ID'),
    sa.Column('participant2_id', sa.String(length=50), nullable=False, comment='会话参与者2ID'),
    sa.Column('participant1_unread', sa.Integer(), nullable=True, comment='参与者1的未读消息数'),
    sa.Column('participant2_unread', sa.Integer(), nullable=True, comment='参与者2的未读消息数'),
    sa.Column('last_message', sa.Text(), nullable=True, comment='最后一条消息内容'),
    sa.Column('last_message_time', sa.Integer(), nullable=True, comment='最后消息时间戳'),
    sa.Column('created_at', sa.Integer(), nullable=True, comment='创建时间戳'),
    sa.Column('updated_at', sa.Integer(), nullable=True, comment='更新时间戳'),
    sa.ForeignKeyConstraint(['participant1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['participant2_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_table('quick_replies',
    sa.Column('id', sa.Integer(), nullable=False, comment='自增主键'),
    sa.Column('user_id', sa.String(length=50), nullable=False, comment='用户ID'),
    sa.Column('content', sa.Text(), nullable=False, comment='快捷回复内容'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序权重'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_at', sa.Integer(), nullable=True, comment='创建时间戳'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quick_replies_id'), 'quick_replies', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False, comment='自增主键'),
    sa.Column('conversation_id', sa.Integer(), nullable=False, comment='会话ID'),
    sa.Column('sender_id', sa.String(length=50), nullable=False, comment='发送者ID'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('message_type', sa.Enum('text', 'image', 'file', name='messagetype'), nullable=True, comment='消息类型：text/image/file'),
    sa.Column('is_read', sa.Boolean(), nullable=True, comment='是否已读'),
    sa.Column('created_at', sa.Integer(), nullable=True, comment='创建时间戳'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_quick_replies_id'), table_name='quick_replies')
    op.drop_table('quick_replies')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
